
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-gateway.fullname" . }}-env
data:
  RATE_LIMIT_CAPACITY: "{{ .Values.rateLimit.capacity | default 200 }}"
  RATE_LIMIT_REFILL_PER_SEC: "{{ .Values.rateLimit.refillPerSec | default 2 }}"
  {{- if .Values.redis.enabled }}
  REDIS_URL: "{{ .Values.redis.url }}"
  {{- end }}
