
apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-gateway.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "payment-gateway.name" . }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
