
replicaCount: 3
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /api/health
vault:
  enabled: true
  injector: true
  role: payment-gateway-role
redis:
  enabled: true
  url: redis://payment-redis-master:6379
