
name: Flyway Migrations (staging -> prod)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'target environment (staging|prod)'
        required: true
        default: staging

jobs:
  migrate-staging:
    if: ${{ github.event.inputs.target == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Flyway on staging
        uses: docker://flyway/flyway:9.16.1
        with:
          args: -url=jdbc:postgresql://${{ secrets.STAGING_PG_HOST }}:${{ secrets.STAGING_PG_PORT }} -user=${{ secrets.STAGING_PG_USER }} -password=${{ secrets.STAGING_PG_PASSWORD }} -locations=filesystem:infra/flyway/sql migrate

  approve-production:
    if: ${{ github.event.inputs.target == 'prod' }}
    runs-on: ubuntu-latest
    needs: []
    environment: production
    steps:
      - name: Await approval
        run: echo "This job requires manual approval via GitHub Environments. Approve to continue."

  migrate-production:
    if: ${{ github.event.inputs.target == 'prod' }}
    runs-on: ubuntu-latest
    needs: [approve-production]
    steps:
      - uses: actions/checkout@v4
      - name: Run Flyway on production (maintenance window recommended)
        uses: docker://flyway/flyway:9.16.1
        with:
          args: -url=jdbc:postgresql://${{ secrets.PROD_PG_HOST }}:${{ secrets.PROD_PG_PORT }} -user=${{ secrets.PROD_PG_USER }} -password=${{ secrets.PROD_PG_PASSWORD }} -locations=filesystem:infra/flyway/sql migrate
